version: "1.0"
instances:

  mariadb:
    build:
      context: ./mariadb
    volumes:
      - ./mariadb/data:/data
    ports:
      - "3306"
    post:
      command: ["/bin/bash", "./mariadb/run_post.sh"]
