name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.0.0
    - name: Download Singularity GitHub Release
      uses: Legion2/download-release-action@v2.0.0
      with:
        repository: sylabs/singularity
        tag: v3.5.0
        path: downloads
        file: singularity-3.5.0.tar.gz
    - name: Install Singularity
      run: |
        tar -xzf downloads/singularity-3.5.0.tar.gz
        cd singularity
        ./mconfig
        make -C builddir
        make -C builddir install
    - name: Install Singularity Compose
      run: |
        apt-get install python3-pip
        sudo -H pip3 install singularity-compose
    - name: Run a one-line script
      run: echo Build complete!
