name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Add GoLang PPA
      run: add-apt-repository ppa:longsleep/golang-backports
    - name: Add dependencies
      run: |
        apt-get update
        apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev wget pkg-config git golang-go
    - name: Download Singularity GitHub Release
      uses: Legion2/download-release-action@v2.0.0
      with:
        repository: sylabs/singularity
        tag: 3.3.0
        path: downloads
        file: singularity-3.3.0.tar.gz
    - name: Install Singularity
      run: |
        cd downloads
        tar -xzf singularity-3.3.0.tar.gz
        cd singularity
        ./mconfig
        make -C builddir
        make -C builddir install
    - name: Install Singularity Compose
      run: |
        apt-get install python3-pip
        sudo -H pip3 install singularity-compose
    - name: Run a one-line script
      run: echo Build complete!
