name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Download Singularity sources from GitHub Release
      uses: Legion2/download-release-action@v2.0.0
      with:
        repository: sylabs/singularity
        tag: v3.5.0
        path: downloads
        file: singularity-3.5.0.tar.gz
    - name: Make Install Singularity
      env:
        SINGULARITY_VERSION: 3.5.0
      run: scripts/install_singularity.sh
    - name: Install Singularity Compose
      run: scripts/install_singularity_compose.sh
    - name: Build the app
      run: scripts/build_containers.sh
