name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Download Singularity sources from GitHub Release
      uses: Legion2/download-release-action@v2.0.0
      with:
        repository: sylabs/singularity
        tag: v3.5.0
        path: downloads
        file: singularity-3.5.0.tar.gz
    - name: Dependencies
      run: |
        sudo apt-get install -y \
        uuid-dev \
        libssl-dev \
        uuid-dev \
        libgpgme11-dev \
        squashfs-tools \
        libseccomp-dev \
        pkg-config \
        python3-setuptools
    - name: Make Install Singularity
      run: |
        tar -xzf downloads/singularity-3.5.0.tar.gz
        cd singularity
        ./mconfig
        make -C builddir
        sudo make -C builddir install
    - name: Install Singularity Compose
      run: |
        sudo -H pip3 install singularity-compose
    - name: Build the app
      run: |
        cd containers
        singularity-compose build

