name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download Go binary
      uses: engineerd/configurator@v0.0.1
      with:
        name: "go"
        url: https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
        pathInArchive: "bin"
    - name: Go status
      run: go --version
    - name: Download Singularity sources from GitHub Release
      uses: Legion2/download-release-action@v2.0.0
      with:
        repository: sylabs/singularity
        tag: v3.5.0
        path: downloads
        file: singularity-3.5.0.tar.gz
    - name: Make Install Singularity
      run: |
        tar -xzf downloads/singularity-3.5.0.tar.gz
        cd singularity
        ./mconfig
        make -C builddir
        make -C builddir install
    - name: Install Singularity Compose
      run: |
        apt-get install python3-pip
        sudo -H pip3 install singularity-compose
    - name: Run a one-line script
      run: echo Build complete!
